id: PC37C38C2
initial_creation_type: input
source_metadata:
  title: Copper-Coloured Mountain
  language: bo
  description: 'Texts related to the Copper-Coloured Mountain of Glory (zangs mdog
    dpal ri), the heaven of Guru Padmasambhava:'
  volume:
    91419e98230747e58e2f47b631343b98:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    9183646f678346bfac8ec95aaf2b2524:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    9f0c6424b20f451b8d5e5e3866579430:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Aspiration Prayers
    d85a8652582145bc80301fb93f6a9469:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Aspiration Prayers
    37d7dea905a94d67b82314a8a6d879a6:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Aspiration Prayers
    1dddf0ff191e4ee4b4aa9c7be853769b:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Aspiration Prayers
    fe3729bb9abe497cae1bc329d7d0f155:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Aspiration Prayers
created_at: '2022-03-01T03:20:07.634457'
last_modified_at: '2022-03-01T03:20:07.634459'
statistics:
  total_words: 3903
  total_non_words: 260
quality:
  non_words_ratio: 0.07
